title: Kenneth Ballenegger
description: |
  Hi, I'm Kenneth. I’m a Swiss transplant in San Francisco. I’m
  an <a href="https://angel.co/kb">angel investor</a>, and an engineer at <a
  href="https://angel.co">AngelList</a> & <a
  href="http://cscventurecapital.com">CSC</a>.  Previously, I was co-founder of
  <a href="https://angel.co/freshpay">FreshPay</a> and the architect behind <a
  href="https://www.chartboost.com">Chartboost</a>. When I'm not working, you
  can find me either photographing some remote corner of the world, or hacking
  away on an ever-changing side project.


permalink: "/:year-:month-:day/:title"
paginate: 10
paginate_path: 'p/:num'
exclude: [bin, backend, public]
gems: [jekyll-paginate]
