title: Kenneth Ballenegger
description: |
    Hi there. My name is Kenneth and I’m a Swiss transplant in San Francisco. I’m co-founder & CTO at <a href="http://hello.freshpay.com/">FreshPay</a>. Previously, I was the architect behind <a href="https://www.chartboost.com">Chartboost</a>. When I'm not working, you can find me either photographing some corner of the world, or hacking away on an ever-changing side project.


permalink: "/:year-:month-:day/:title"
paginate: 10
exclude: [bin, backend, public]
